package e03

// Excercise 01: Inline defs
// Try to change the log method in such a way that it only adds the overheade to the execution when loggingEnabled is true.
// To check the generated bytecode you can use the following commands:
//    scala-cli compile 03-inline-params-cont -d out
//    jjavap -v out.e03.logger\$package\$

val loggingEnabled: false = false

inline def log(inline msg: String): Unit =
  inline if loggingEnabled then println(msg)

def square(x: Int): Int =
  log(s"square($x)")
  val res = x * x
  log(s"square($x) = $res")
  res